package com.deportel.componentes.modelo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AccionAplicacion generated by hbm2java
 */
@Entity
@Table(name = "accion_componente", catalog = "componentes")
public class AccionComponente implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	private Integer				CId;

	@Column(name = "d_nombre", length = 45)
	private String				DNombre;

	@Column(name = "c_codigo", nullable = false, length = 45)
	private String				CCodigo;

	@Column(name = "d_descripcion", length = 200)
	private String				DDescripcion;

	@Column(name = "m_habilitada", nullable = false, length = 1)
	private String				MHabilitada;

	public AccionComponente()
	{
	}

	public AccionComponente(String CCodigo, String MHabilitada)
	{
		this.CCodigo = CCodigo;
		this.MHabilitada = MHabilitada;
	}

	public AccionComponente(String DNombre, String CCodigo, String DDescripcion, String MHabilitada)
	{
		this.DNombre = DNombre;
		this.CCodigo = CCodigo;
		this.DDescripcion = DDescripcion;
		this.MHabilitada = MHabilitada;
	}

	public Integer getCId ()
	{
		return this.CId;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public String getDNombre ()
	{
		return this.DNombre;
	}

	public void setDNombre (String DNombre)
	{
		this.DNombre = DNombre;
	}
	public String getCCodigo ()
	{
		return this.CCodigo;
	}

	public void setCCodigo (String CCodigo)
	{
		this.CCodigo = CCodigo;
	}

	public String getDDescripcion ()
	{
		return this.DDescripcion;
	}

	public void setDDescripcion (String DDescripcion)
	{
		this.DDescripcion = DDescripcion;
	}

	public String getMHabilitada ()
	{
		return this.MHabilitada;
	}

	public void setMHabilitada (String MHabilitada)
	{
		this.MHabilitada = MHabilitada;
	}

	@Override
	public String toString ()
	{
		StringBuilder sb = new StringBuilder();
		sb
		.append("Codigo: " + this.CCodigo + " ")
		.append("Nombre: " + this.DNombre + " ")
		.append("Descripcion: " + this.DDescripcion);
		return sb.toString();
	}
}
