package com.deportel.componentes.modelo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AlineacionComponente generated by hbm2java
 */
@Entity
@Table(name = "alineacion_componente", catalog = "componentes")
public class AlineacionComponente implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	private Integer	CId;
	private String	CCodigo;
	private String	DNombre;
	private String	DDescripcion;

	public AlineacionComponente()
	{
	}

	public AlineacionComponente(String CCodigo)
	{
		this.CCodigo = CCodigo;
	}

	public AlineacionComponente(String CCodigo, String DNombre, String DDescripcion)
	{
		this.CCodigo = CCodigo;
		this.DNombre = DNombre;
		this.DDescripcion = DDescripcion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	public Integer getCId ()
	{
		return this.CId;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	@Column(name = "c_codigo", nullable = false, length = 3)
	public String getCCodigo ()
	{
		return this.CCodigo;
	}

	public void setCCodigo (String CCodigo)
	{
		this.CCodigo = CCodigo;
	}

	@Column(name = "d_nombre", length = 45)
	public String getDNombre ()
	{
		return this.DNombre;
	}

	public void setDNombre (String DNombre)
	{
		this.DNombre = DNombre;
	}

	@Column(name = "d_descripcion", length = 200)
	public String getDDescripcion ()
	{
		return this.DDescripcion;
	}

	public void setDDescripcion (String DDescripcion)
	{
		this.DDescripcion = DDescripcion;
	}

	@Override
	public String toString ()
	{
		StringBuilder sb = new StringBuilder();
		sb
		.append("Codigo: " + this.CCodigo + " ")
		.append("Nombre: " + this.DNombre + " ")
		.append("Descripcion: " + this.DDescripcion);
		return sb.toString();
	}
}
