package com.deportel.componentes.modelo;

// Generated 15/09/2011 22:54:04 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "componentes")
public class Cliente /*extends FutboltelEntity*/ implements java.io.Serializable
{
	private static final long	serialVersionUID	= -2292008332709643973L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	private Integer				id;

	@Column(name = "d_nombre", length = 50)
	private String				nombre;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	private Set<Transaccion>	transacciones	= new HashSet<Transaccion>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	private Set<Suscripcion>	suscripciones	= new HashSet<Suscripcion>(0);

	public Cliente()
	{
	}

	public Cliente(String nombre)
	{
		this.nombre = nombre;
	}

	public Integer getId ()
	{
		return this.id;
	}

	public void setId (Integer id)
	{
		this.id = id;
	}

	public String getNombre ()
	{
		return this.nombre;
	}

	public void setNombre (String nombre)
	{
		this.nombre = nombre;
	}

	public Set<Transaccion> getTransacciones ()
	{
		return this.transacciones;
	}

	public void setTransacciones (Set<Transaccion> transacciones)
	{
		this.transacciones = transacciones;
	}

	public Set<Suscripcion> getSuscripciones ()
	{
		return this.suscripciones;
	}

	public void setSuscripciones (Set<Suscripcion> suscripciones)
	{
		this.suscripciones = suscripciones;
	}

}
