package com.deportel.componentes.modelo;

// Generated 30/09/2011 18:55:03 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ParametrosConsulta generated by hbm2java
 */
@Entity
@Table(name = "parametro_consulta", catalog = "componentes")
public class ParametroConsulta /*extends FutboltelEntity*/ implements Comparable<ParametroConsulta>, java.io.Serializable
{
	private static final long	serialVersionUID	= 5900329846586984017L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	private Integer				CId;

	@Column(name = "m_tipo_salida", nullable = false, length = 1)
	private String				MTipoSalida;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "consulta_c_id", nullable = false)
	private ConsultaDinamica	consultaDinamica;

	@Column(name = "d_tipo_dato", nullable = false, length = 45)
	private String				tipoDato;

	@Column(name = "d_nombre", nullable = false, length = 45)
	private String				nombre;

	@Column(name = "n_indice")
	private Integer				indice;

	public ParametroConsulta()
	{
	}

	public ParametroConsulta(String MTipoSalida, String tipoDatoParametro, String nombreParametro)
	{
		this.MTipoSalida = MTipoSalida;
		this.tipoDato = tipoDatoParametro;
		this.nombre = nombreParametro;
	}

	public Integer getCId ()
	{
		return this.CId;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public String getMTipoSalida ()
	{
		return this.MTipoSalida;
	}

	public void setMTipoSalida (String MTipoSalida)
	{
		this.MTipoSalida = MTipoSalida;
	}

	public ConsultaDinamica getConsultaDinamica ()
	{
		return this.consultaDinamica;
	}

	public void setConsultaDinamica (ConsultaDinamica consultaDinamica)
	{
		this.consultaDinamica = consultaDinamica;
	}

	public String getTipoDato ()
	{
		return this.tipoDato;
	}

	public void setTipoDato (String tipoDato)
	{
		this.tipoDato = tipoDato;
	}

	public String getNombre ()
	{
		return this.nombre;
	}

	public void setNombre (String nombre)
	{
		this.nombre = nombre;
	}

	public Integer getIndice ()
	{
		return this.indice;
	}

	public void setIndice (Integer indice)
	{
		this.indice = indice;
	}

	/* (non-Javadoc)
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 */
	@Override
	public int compareTo (ParametroConsulta o)
	{
		if (o != null)
		{
			if (this.getIndice() != null && o.getIndice() != null)
			{
				return this.getIndice() - o.getIndice();
			}
		}
		return 0;
	}
}
