package com.deportel.componentes.modelo;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ServicioSoporte generated by hbm2java
 */
@Entity
@Table(name = "servicio_soporte", catalog = "componentes")
public class ServicioSoporte implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	private Integer	CId;
	private Tema	tema;
	private String	DNombre;
	private String	DConsulta;

	public ServicioSoporte()
	{
	}

	public ServicioSoporte(Tema tema, String DNombre, String DConsulta)
	{
		this.tema = tema;
		this.DNombre = DNombre;
		this.DConsulta = DConsulta;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	public Integer getCId ()
	{
		return this.CId;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tema_c_id", nullable = false)
	public Tema getTema ()
	{
		return this.tema;
	}

	public void setTema (Tema tema)
	{
		this.tema = tema;
	}

	@Column(name = "d_nombre", nullable = false, length = 45)
	public String getDNombre ()
	{
		return this.DNombre;
	}

	public void setDNombre (String DNombre)
	{
		this.DNombre = DNombre;
	}

	@Column(name = "d_consulta", nullable = false, length = 65535)
	public String getDConsulta ()
	{
		return this.DConsulta;
	}

	public void setDConsulta (String DConsulta)
	{
		this.DConsulta = DConsulta;
	}

	public static final String	FIELD_NAME		= "DNombre";
}
