package com.deportel.componentes.modelo;

// Generated 15/09/2011 22:54:04 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoComponente generated by hbm2java
 */
@Entity
@Table(name = "tipo_componente", catalog = "componentes")
public class TipoComponente /*extends FutboltelEntity*/ implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	private Integer				CId;

	@Column(name = "d_nombre", length = 45, nullable = false)
	private String				DNombre;

	@Column(name = "d_descripcion", length = 300)
	private String				DDescripcion;

	@Column(name = "d_tag_xml", length = 45, nullable = false)
	private String				DTagXml;

	@Column(name = "c_tipo_componente", nullable = false)
	private int					CTipoComponente;

	@Column(name = "m_sirve_contenido", length = 1, nullable = false)
	private String				MSirveContenido;

	public TipoComponente()
	{
	}

	public TipoComponente(String DNombre, String DDescripcion, String DTagXml)
	{
		this.DNombre = DNombre;
		this.DDescripcion = DDescripcion;
		this.DTagXml = DTagXml;
	}

	public Integer getCid ()
	{
		return this.CId;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public String getDNombre ()
	{
		return this.DNombre;
	}

	public void setDNombre (String DNombre)
	{
		this.DNombre = DNombre;
	}

	public String getDDescripcion ()
	{
		return this.DDescripcion;
	}

	public void setDDescripcion (String DDescripcion)
	{
		this.DDescripcion = DDescripcion;
	}

	public String getDTagXml ()
	{
		return this.DTagXml;
	}

	public void setDTagXml (String DTagXml)
	{
		this.DTagXml = DTagXml;
	}

	public void setCTipoComponente (int cTipoComponente)
	{
		this.CTipoComponente = cTipoComponente;
	}

	public int getCTipoComponente ()
	{
		return this.CTipoComponente;
	}

	public void setMSirveContenido (String mSirveContenido)
	{
		this.MSirveContenido = mSirveContenido;
	}

	public String getMSirveContenido ()
	{
		return this.MSirveContenido;
	}

	@Override
	public String toString ()
	{
		return this.DNombre;
	}

	@Override
	public int hashCode ()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getCid() == null) ? 0 : getCid().hashCode());
		return result;
	}

	@Override
	public boolean equals (Object obj)
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		TipoComponente other = (TipoComponente) obj;
		if (getCid() == null)
		{
			if (other.getCid() != null)
				return false;
		}
		else if (!getCid().equals(other.getCid()))
			return false;
		return true;
	}

	public static final String	FIELD_NAME		= "DNombre";
	public static final String	FIELD_XML_TAG	= "DTagXml";
}
