package com.deportel.componentes.modelo;

// Generated 15/09/2011 22:54:04 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TipoPropiedad generated by hbm2java
 */
@Entity
@Table(name = "tipo_propiedad", catalog = "componentes", uniqueConstraints = @UniqueConstraint(columnNames = "d_tag_xml"))
public class TipoPropiedad /*extends FutboltelEntity*/ implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	private Integer				CId;

	@Column(name = "d_nombre", length = 45)
	private String				DNombre;

	@Column(name = "d_descripcion", length = 300)
	private String				DDescripcion;

	@Column(name = "d_tag_xml", unique = true, nullable = false, length = 45)
	private String				DTagXml;

	@Column(name = "c_tipo_propiedad")
	private int					CTipoPropiedad;

	@Column(name = "d_tipo_dato")
	private String				DTipoDato;

	public TipoPropiedad()
	{
	}

	public TipoPropiedad(String DTagXml)
	{
		this.DTagXml = DTagXml;
	}

	public TipoPropiedad(String DNombre, String DDescripcion, String DTagXml)
	{
		this.DNombre = DNombre;
		this.DDescripcion = DDescripcion;
		this.DTagXml = DTagXml;
	}

	public Integer getCId ()
	{
		return this.CId;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public String getDNombre ()
	{
		return this.DNombre;
	}

	public void setDNombre (String DNombre)
	{
		this.DNombre = DNombre;
	}

	public String getDDescripcion ()
	{
		return this.DDescripcion;
	}

	public void setDDescripcion (String DDescripcion)
	{
		this.DDescripcion = DDescripcion;
	}

	public String getDTagXml ()
	{
		return this.DTagXml;
	}

	public void setDTagXml (String DTagXml)
	{
		this.DTagXml = DTagXml;
	}

	public void setCTipoPropiedad (int cTipoPropiedad)
	{
		this.CTipoPropiedad = cTipoPropiedad;
	}

	public int getCTipoPropiedad ()
	{
		return this.CTipoPropiedad;
	}

	public void setDTipoDato (String dTipoDato)
	{
		this.DTipoDato = dTipoDato;
	}

	public String getDTipoDato ()
	{
		return this.DTipoDato;
	}

	@Override
	public int hashCode ()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((this.CId == null) ? 0 : this.CId.hashCode());
		return result;
	}

	@Override
	public boolean equals (Object obj)
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		TipoPropiedad other = (TipoPropiedad) obj;
		if (this.getCId() == null)
		{
			if (other.getCId() != null)
				return false;
		}
		else if (!this.getCId().equals(other.getCId()))
			return false;
		return true;
	}

	public static final String	TAG_ID				= "id";
	public static final String	TAG_X_POS			= "rcx";
	public static final String	TAG_Y_POS			= "rcy";
	public static final String	TAG_HEIGHT			= "rch";
	public static final String	TAG_WIDTH			= "rcw";
	public static final String	TAG_TEXT			= "text";
	public static final String	TAG_NAME			= "name";
	public static final String	TAG_ACTION			= "action";
	public static final String	TAG_ACTION_PARAMS	= "aparam";
	public static final String	TAG_DATA			= "data";
	public static final String	TAG_DATA_DESC		= "desc";
	public static final String	TAG_FATHER			= "father";
	public static final String	TAG_UPDATE_TIME		= "uti";
	public static final String	TAG_TEXT_LIMIT		= "textLim";
	public static final String	TAG_SUBTYPE			= "type";
	public static final String	TAG_FONT_TYPE		= "fty";
	public static final String	TAG_TEXT_ALIGN		= "tal";
	public static final String	TAG_MAR_X			= "marx";
	public static final String	TAG_MAR_Y			= "mary";
	public static final String	TAG_CHILDS			= "childs";
	public static final String	TAG_TIME_STAMP		= "tstamp";
	public static final String	TAG_ANCHOR			= "anc";
	public static final String	TAG_FG_COLOR		= "fgc";
	public static final String	TAG_BG_COLOR		= "bgc";
	public static final String	TAG_AL_COLOR		= "alc";
	public static final String	TAG_IMAGE_SOURCE	= "img";

	public static interface DataTypes
	{
		public static final String	BYTE			= "BYTE";
		public static final String	HEXA_BYTE		= "HBYTE";
		public static final String	SHORT			= "SHORT";
		public static final String	HEXA_SHORT		= "HSHORT";
		public static final String	INTEGER			= "INT";
		public static final String	HEXA_INTEGER	= "IHNT";
		public static final String	LONG			= "LONG";
		public static final String	HEXA_LONG		= "HLONG";
		public static final String	STRING			= "STRING";
	}

	public static final String	FIELD_NAME		= "DNombre";
	public static final String	FIELD_XML_TAG	= "DTagXml";
}
