package com.deportel.componentes.modelo;

// Generated 15/09/2011 22:54:04 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaccion generated by hbm2java
 */
@Entity
@Table(name = "transaccion", catalog = "componentes")
public class Transaccion /*extends FutboltelEntity*/ implements java.io.Serializable
{
	private static final long	serialVersionUID	= -2602572405199077213L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	private Integer				CId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cliente_c_id", nullable = true)
	private Cliente				cliente;

	@Column(name = "n_duracion")
	private long				duracion;

	@Temporal(TemporalType.DATE)
	@Column(name = "f_fecha", length = 10)
	private Date				FFecha;

	public Transaccion()
	{
	}

	public Transaccion(Cliente cliente)
	{
		this.cliente = cliente;
	}

	public Transaccion(Cliente cliente, Date FFecha, long elapsed)
	{
		this.cliente = cliente;
		this.FFecha = FFecha;
		this.duracion = elapsed;
	}

	public Integer getCId ()
	{
		return this.CId;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public Cliente getCliente ()
	{
		return this.cliente;
	}

	public void setCliente (Cliente cliente)
	{
		this.cliente = cliente;
	}

	public Date getFFecha ()
	{
		return this.FFecha;
	}

	public void setFFecha (Date FFecha)
	{
		this.FFecha = FFecha;
	}

	public void setDuracion (long duracion)
	{
		this.duracion = duracion;
	}

	public long getDuracion ()
	{
		return this.duracion;
	}

}
