package com.deportel.administracion.modelo;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ModuloPerfil generated by hbm2java
 */
@Entity
@Table(name = "modulo_perfil", catalog = "administracion")
public class ModuloPerfil implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	private Integer				CId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "perfil_c_id", nullable = false)
	private Perfil				perfil;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modulo_c_id", nullable = false)
	private Modulo				modulo;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_permiso_c_id", nullable = false)
	private TipoPermiso			tipoPermiso;

	public ModuloPerfil()
	{
	}

	public ModuloPerfil(Perfil perfil, Modulo modulo, TipoPermiso tipoPermiso)
	{
		this.perfil = perfil;
		this.modulo = modulo;
		this.tipoPermiso = tipoPermiso;
	}

	public Integer getCId ()
	{
		return this.CId;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public Perfil getPerfil ()
	{
		return this.perfil;
	}

	public void setPerfil (Perfil perfil)
	{
		this.perfil = perfil;
	}

	public Modulo getModulo ()
	{
		return this.modulo;
	}

	public void setModulo (Modulo modulo)
	{
		this.modulo = modulo;
	}

	public TipoPermiso getTipoPermiso ()
	{
		return this.tipoPermiso;
	}

	public void setTipoPermiso (TipoPermiso tipoPermiso)
	{
		this.tipoPermiso = tipoPermiso;
	}

	@Override
	public int hashCode ()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((this.modulo == null) ? 0 : this.modulo.hashCode());
		result = prime * result + ((this.perfil == null) ? 0 : this.perfil.hashCode());
		result = prime * result + ((this.tipoPermiso == null) ? 0 : this.tipoPermiso.hashCode());
		return result;
	}

	@Override
	public boolean equals (Object obj)
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ModuloPerfil other = (ModuloPerfil) obj;
		if (this.modulo == null)
		{
			if (other.modulo != null)
				return false;
		}
		else if (!this.modulo.equals(other.modulo))
			return false;
		if (this.perfil == null)
		{
			if (other.perfil != null)
				return false;
		}
		else if (!this.perfil.equals(other.perfil))
			return false;
		if (this.tipoPermiso == null)
		{
			if (other.tipoPermiso != null)
				return false;
		}
		else if (!this.tipoPermiso.equals(other.tipoPermiso))
			return false;
		return true;
	}


}
