package com.deportel.administracion.modelo;

// Generated 05/04/2012 23:09:35 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PerfilUsuario generated by hbm2java
 */
@Entity
@Table(name = "perfil_usuario", catalog = "administracion")
public class PerfilUsuario implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	private Integer	CId;


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "perfil_c_id", nullable = false)
	private Perfil	perfil;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_c_id", nullable = false)
	private Usuario	usuario;

	public PerfilUsuario()
	{
	}

	public PerfilUsuario(Perfil perfil, Usuario usuario)
	{
		this.perfil = perfil;
		this.usuario = usuario;
	}

	public Integer getCId ()
	{
		return this.CId;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public Perfil getPerfil ()
	{
		return this.perfil;
	}

	public void setPerfil (Perfil perfil)
	{
		this.perfil = perfil;
	}

	public Usuario getUsuario ()
	{
		return this.usuario;
	}

	public void setUsuario (Usuario usuario)
	{
		this.usuario = usuario;
	}

}
