package com.deportel.futboltel.torneo.modelo;

// Generated 30/01/2011 15:37:39 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cancha generated by hbm2java
 */
@Entity
@Table(name = "cancha", catalog = "torneo")
public class Cancha implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;
	
	private Integer				CId;
	private Sede				sede;
	private String				DDescripcion;
	private String				MEstado;
	private Set<Partido>		partidos			= new HashSet<Partido>(0);

	public Cancha()
	{
	}

	public Cancha(Sede sede)
	{
		this.sede = sede;
	}

	public Cancha(Sede sede, String DDescripcion, String MEstado, Set<Partido> partidos)
	{
		this.sede = sede;
		this.DDescripcion = DDescripcion;
		this.MEstado = MEstado;
		this.partidos = partidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	public Integer getCId ()
	{
		return this.CId;
	}

	@Column(name = "d_descripcion", length = 45)
	public String getDDescripcion ()
	{
		return this.DDescripcion;
	}

	@Column(name = "m_estado", length = 1)
	public String getMEstado ()
	{
		return this.MEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cancha")
	public Set<Partido> getPartidos ()
	{
		return this.partidos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sede_c_id", nullable = false)
	public Sede getSede ()
	{
		return this.sede;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public void setDDescripcion (String DDescripcion)
	{
		this.DDescripcion = DDescripcion;
	}

	public void setMEstado (String MEstado)
	{
		this.MEstado = MEstado;
	}

	public void setPartidos (Set<Partido> partidos)
	{
		this.partidos = partidos;
	}

	public void setSede (Sede sede)
	{
		this.sede = sede;
	}

}
