package com.deportel.futboltel.torneo.modelo;

// Generated 30/01/2011 15:37:39 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria", catalog = "torneo")
public class Categoria implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	private Integer				CId;

	@Column(name = "d_nombre", length = 45)
	private String				DNombre;

	@Column(name = "d_descripcion", length = 300)
	private String				DDescripcion;

	@Column(name = "m_estado", length = 1)
	private String				MEstado;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	private Set<Equipo>			equipos				= new HashSet<Equipo>(0);

	//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	//	private Set<Torneo>			torneos				= new HashSet<Torneo>(0);

	public Categoria()
	{
	}

	public Categoria(String DNombre, String DDescripcion, String MEstado, Set<Equipo> equipos)
	{
		this.DNombre = DNombre;
		this.DDescripcion = DDescripcion;
		this.MEstado = MEstado;
		this.equipos = equipos;
	}

	public Integer getCId ()
	{
		return this.CId;
	}

	public String getDDescripcion ()
	{
		return this.DDescripcion;
	}

	public String getDNombre ()
	{
		return this.DNombre;
	}

	public Set<Equipo> getEquipos ()
	{
		return this.equipos;
	}

	public String getMEstado ()
	{
		return this.MEstado;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public void setDDescripcion (String DDescripcion)
	{
		this.DDescripcion = DDescripcion;
	}

	public void setDNombre (String DNombre)
	{
		this.DNombre = DNombre;
	}

	public void setEquipos (Set<Equipo> equipos)
	{
		this.equipos = equipos;
	}

	public void setMEstado (String MEstado)
	{
		this.MEstado = MEstado;
	}

	public static final String	FIELD_STATE	= "MEstado";
}
