package com.deportel.futboltel.torneo.modelo;

// Generated 30/01/2011 15:37:39 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Evento generated by hbm2java
 */
@Entity
@Table(name = "evento", catalog = "torneo")
public class Evento implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;
	
	private Integer				CId;
	private TipoEvento			tipoEvento;
	private Equipo				equipo;
	private Partido				partido;
	private Fecha				fecha;
	private Sancion				sancion;
	private String				MEstado;
	private Set<EventoJugador>	eventoJugadors		= new HashSet<EventoJugador>(0);

	public Evento()
	{
	}

	public Evento(TipoEvento tipoEvento, Equipo equipo, Partido partido)
	{
		this.tipoEvento = tipoEvento;
		this.equipo = equipo;
		this.partido = partido;
	}

	public Evento(TipoEvento tipoEvento, Equipo equipo, Partido partido, Fecha fecha, Sancion sancion, String MEstado, Set<EventoJugador> eventoJugadors)
	{
		this.tipoEvento = tipoEvento;
		this.equipo = equipo;
		this.partido = partido;
		this.fecha = fecha;
		this.sancion = sancion;
		this.MEstado = MEstado;
		this.eventoJugadors = eventoJugadors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	public Integer getCId ()
	{
		return this.CId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "equipo_c_id", nullable = false)
	public Equipo getEquipo ()
	{
		return this.equipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evento")
	public Set<EventoJugador> getEventoJugadors ()
	{
		return this.eventoJugadors;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fecha_c_id")
	public Fecha getFecha ()
	{
		return this.fecha;
	}

	@Column(name = "m_estado", length = 1)
	public String getMEstado ()
	{
		return this.MEstado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "partido_c_id", nullable = false)
	public Partido getPartido ()
	{
		return this.partido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sancion_c_id")
	public Sancion getSancion ()
	{
		return this.sancion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_evento_c_id", nullable = false)
	public TipoEvento getTipoEvento ()
	{
		return this.tipoEvento;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public void setEquipo (Equipo equipo)
	{
		this.equipo = equipo;
	}

	public void setEventoJugadors (Set<EventoJugador> eventoJugadors)
	{
		this.eventoJugadors = eventoJugadors;
	}

	public void setFecha (Fecha fecha)
	{
		this.fecha = fecha;
	}

	public void setMEstado (String MEstado)
	{
		this.MEstado = MEstado;
	}

	public void setPartido (Partido partido)
	{
		this.partido = partido;
	}

	public void setSancion (Sancion sancion)
	{
		this.sancion = sancion;
	}

	public void setTipoEvento (TipoEvento tipoEvento)
	{
		this.tipoEvento = tipoEvento;
	}

}
