package com.deportel.futboltel.torneo.modelo;

// Generated 30/01/2011 15:37:39 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EventoJugador generated by hbm2java
 */
@Entity
@Table(name = "evento_jugador", catalog = "torneo")
public class EventoJugador implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	private Integer				CId;
	private Jugador				jugador;
	private Evento				evento;

	public EventoJugador()
	{
	}

	public EventoJugador(Jugador jugador, Evento evento)
	{
		this.jugador = jugador;
		this.evento = evento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	public Integer getCId ()
	{
		return this.CId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "evento_c_id", nullable = false)
	public Evento getEvento ()
	{
		return this.evento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jugador_c_id", nullable = false)
	public Jugador getJugador ()
	{
		return this.jugador;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public void setEvento (Evento evento)
	{
		this.evento = evento;
	}

	public void setJugador (Jugador jugador)
	{
		this.jugador = jugador;
	}

}
