package com.deportel.futboltel.torneo.modelo;

// Generated 30/01/2011 15:37:39 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fecha generated by hbm2java
 */
@Entity
@Table(name = "fecha", catalog = "torneo")
public class Fecha implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	private Integer				CId;
	private Torneo				torneo;
	private Date				FFecha;
	private Integer				NNumero;
	private String				MEstado;
	private Set<Evento>			eventos				= new HashSet<Evento>(0);
	private Set<Partido>		partidos			= new HashSet<Partido>(0);

	public Fecha()
	{
	}

	public Fecha(Torneo torneo, Date FFecha)
	{
		this.torneo = torneo;
		this.FFecha = FFecha;
	}

	public Fecha(Torneo torneo, Date FFecha, Integer NNumero, String MEstado, Set<Evento> eventos, Set<Partido> partidos)
	{
		this.torneo = torneo;
		this.FFecha = FFecha;
		this.NNumero = NNumero;
		this.MEstado = MEstado;
		this.eventos = eventos;
		this.partidos = partidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	public Integer getCId ()
	{
		return this.CId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fecha")
	public Set<Evento> getEventos ()
	{
		return this.eventos;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "f_fecha", nullable = false, length = 10)
	public Date getFFecha ()
	{
		return this.FFecha;
	}

	@Column(name = "m_estado", length = 1)
	public String getMEstado ()
	{
		return this.MEstado;
	}

	@Column(name = "n_numero")
	public Integer getNNumero ()
	{
		return this.NNumero;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fecha")
	public Set<Partido> getPartidos ()
	{
		return this.partidos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "torneo_c_id", nullable = false)
	public Torneo getTorneo ()
	{
		return this.torneo;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public void setEventos (Set<Evento> eventos)
	{
		this.eventos = eventos;
	}

	public void setFFecha (Date FFecha)
	{
		this.FFecha = FFecha;
	}

	public void setMEstado (String MEstado)
	{
		this.MEstado = MEstado;
	}

	public void setNNumero (Integer NNumero)
	{
		this.NNumero = NNumero;
	}

	public void setPartidos (Set<Partido> partidos)
	{
		this.partidos = partidos;
	}

	public void setTorneo (Torneo torneo)
	{
		this.torneo = torneo;
	}

}
