package com.deportel.futboltel.torneo.modelo;

// Generated 30/01/2011 15:37:39 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name = "horario", catalog = "torneo")
public class Horario implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;
	
	private Integer				CId;
	private Integer				NHora;
	private Integer				NMinuto;
	private Set<Partido>		partidos			= new HashSet<Partido>(0);

	public Horario()
	{
	}

	public Horario(Integer NHora, Integer NMinuto, Set<Partido> partidos)
	{
		this.NHora = NHora;
		this.NMinuto = NMinuto;
		this.partidos = partidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	public Integer getCId ()
	{
		return this.CId;
	}

	@Column(name = "n_hora")
	public Integer getNHora ()
	{
		return this.NHora;
	}

	@Column(name = "n_minuto")
	public Integer getNMinuto ()
	{
		return this.NMinuto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "horario")
	public Set<Partido> getPartidos ()
	{
		return this.partidos;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public void setNHora (Integer NHora)
	{
		this.NHora = NHora;
	}

	public void setNMinuto (Integer NMinuto)
	{
		this.NMinuto = NMinuto;
	}

	public void setPartidos (Set<Partido> partidos)
	{
		this.partidos = partidos;
	}

}
