package com.deportel.futboltel.torneo.modelo;

// Generated 30/01/2011 15:37:39 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Jugador generated by hbm2java
 */
@Entity
@Table(name = "jugador", catalog = "torneo")
public class Jugador implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	private Integer				CId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "equipo_c_id", nullable = false)
	private Equipo				equipo;

	@Column(name = "d_nombre", length = 45)
	private String				DNombre;

	@Column(name = "d_apellido", length = 45)
	private String				DApellido;

	@Column(name = "d_documento", length = 45)
	private String				DDocumento;

	@Column(name = "d_telefono", length = 45)
	private String				DTelefono;

	@Column(name = "d_direccion", length = 45)
	private String				DDireccion;

	@Column(name = "m_delegado", length = 1)
	private Character			MDelegado;

	@Column(name = "m_estado", length = 1)
	private String				MEstado;

	//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jugador")
	//	private Set<JugadorTorneo>	jugadorTorneos		= new HashSet<JugadorTorneo>(0);
	//
	//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jugador")
	//	private Set<EventoJugador>	eventoJugadors		= new HashSet<EventoJugador>(0);
	//
	//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jugador")
	//	private Set<Sancion>		sancions			= new HashSet<Sancion>(0);

	public Jugador()
	{
	}

	public Jugador(Equipo equipo)
	{
		this.equipo = equipo;
	}

	public Integer getCId ()
	{
		return this.CId;
	}

	public String getDApellido ()
	{
		return this.DApellido;
	}

	public String getDDireccion ()
	{
		return this.DDireccion;
	}

	public String getDDocumento ()
	{
		return this.DDocumento;
	}

	public String getDNombre ()
	{
		return this.DNombre;
	}

	public String getDTelefono ()
	{
		return this.DTelefono;
	}

	public Equipo getEquipo ()
	{
		return this.equipo;
	}

	//	public Set<EventoJugador> getEventoJugadors ()
	//	{
	//		return this.eventoJugadors;
	//	}
	//
	//	public Set<JugadorTorneo> getJugadorTorneos ()
	//	{
	//		return this.jugadorTorneos;
	//	}

	public Character getMDelegado ()
	{
		return this.MDelegado;
	}

	public String getMEstado ()
	{
		return this.MEstado;
	}

	//	public Set<Sancion> getSancions ()
	//	{
	//		return this.sancions;
	//	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public void setDApellido (String DApellido)
	{
		this.DApellido = DApellido;
	}

	public void setDDireccion (String DDireccion)
	{
		this.DDireccion = DDireccion;
	}

	public void setDDocumento (String DDocumento)
	{
		this.DDocumento = DDocumento;
	}

	public void setDNombre (String DNombre)
	{
		this.DNombre = DNombre;
	}

	public void setDTelefono (String DTelefono)
	{
		this.DTelefono = DTelefono;
	}

	public void setEquipo (Equipo equipo)
	{
		this.equipo = equipo;
	}

	//	public void setEventoJugadors (Set<EventoJugador> eventoJugadors)
	//	{
	//		this.eventoJugadors = eventoJugadors;
	//	}
	//
	//	public void setJugadorTorneos (Set<JugadorTorneo> jugadorTorneos)
	//	{
	//		this.jugadorTorneos = jugadorTorneos;
	//	}

	public void setMDelegado (Character MDelegado)
	{
		this.MDelegado = MDelegado;
	}

	public void setMEstado (String MEstado)
	{
		this.MEstado = MEstado;
	}

	//	public void setSancions (Set<Sancion> sancions)
	//	{
	//		this.sancions = sancions;
	//	}

}
