package com.deportel.futboltel.torneo.modelo;

// Generated 30/01/2011 15:37:39 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JugadorTorneo generated by hbm2java
 */
@Entity
@Table(name = "jugador_torneo", catalog = "torneo")
public class JugadorTorneo implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	private Integer				CId;
	private Jugador				jugador;
	private Torneo				torneo;
	private Integer				NGoles;

	public JugadorTorneo()
	{
	}

	public JugadorTorneo(Jugador jugador, Torneo torneo)
	{
		this.jugador = jugador;
		this.torneo = torneo;
	}

	public JugadorTorneo(Jugador jugador, Torneo torneo, Integer NGoles)
	{
		this.jugador = jugador;
		this.torneo = torneo;
		this.NGoles = NGoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	public Integer getCId ()
	{
		return this.CId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jugador_c_id", nullable = false)
	public Jugador getJugador ()
	{
		return this.jugador;
	}

	@Column(name = "n_goles")
	public Integer getNGoles ()
	{
		return this.NGoles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "torneo_c_id", nullable = false)
	public Torneo getTorneo ()
	{
		return this.torneo;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public void setJugador (Jugador jugador)
	{
		this.jugador = jugador;
	}

	public void setNGoles (Integer NGoles)
	{
		this.NGoles = NGoles;
	}

	public void setTorneo (Torneo torneo)
	{
		this.torneo = torneo;
	}

}
