package com.deportel.futboltel.torneo.modelo;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Noticia generated by hbm2java
 */
@Entity
@Table(name = "noticia", catalog = "torneo")
public class Noticia implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	private Integer		CId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "equipo_c_id", nullable = false)
	private Equipo		equipo;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoria_c_id", nullable = false)
	private Categoria	categoria;

	@Column(name = "d_nombre", nullable = false, length = 45)
	private String		DNombre;

	@Column(name = "d_noticia", nullable = false, length = 65535)
	private String		DNoticia;

	@Temporal(TemporalType.DATE)
	@Column(name = "f_noticia", length = 10)
	private Date		FNoticia;

	public Noticia()
	{
	}

	public Integer getCId ()
	{
		return this.CId;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public Equipo getEquipo ()
	{
		return this.equipo;
	}

	public void setEquipo (Equipo equipo)
	{
		this.equipo = equipo;
	}

	public Categoria getCategoria ()
	{
		return this.categoria;
	}

	public void setCategoria (Categoria categoria)
	{
		this.categoria = categoria;
	}

	public String getDNombre ()
	{
		return this.DNombre;
	}

	public void setDNombre (String DNombre)
	{
		this.DNombre = DNombre;
	}

	public String getDNoticia ()
	{
		return this.DNoticia;
	}

	public void setDNoticia (String DNoticia)
	{
		this.DNoticia = DNoticia;
	}

	public Date getFNoticia ()
	{
		return this.FNoticia;
	}

	public void setFNoticia (Date FNoticia)
	{
		this.FNoticia = FNoticia;
	}

}
