package com.deportel.futboltel.torneo.modelo;

// Generated 30/01/2011 15:37:39 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sancion generated by hbm2java
 */
@Entity
@Table(name = "sancion", catalog = "torneo")
public class Sancion implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	private Integer				CId;
	private Equipo				equipo;
	private Jugador				jugador;
	private TipoSancion			tipoSancion;
	private String				MEstado;
	private Set<SancionTorneo>	sancionTorneos		= new HashSet<SancionTorneo>(0);
	private Set<Evento>			eventos				= new HashSet<Evento>(0);

	public Sancion()
	{
	}

	public Sancion(Equipo equipo, Jugador jugador, TipoSancion tipoSancion, String MEstado, Set<SancionTorneo> sancionTorneos, Set<Evento> eventos)
	{
		this.equipo = equipo;
		this.jugador = jugador;
		this.tipoSancion = tipoSancion;
		this.MEstado = MEstado;
		this.sancionTorneos = sancionTorneos;
		this.eventos = eventos;
	}

	public Sancion(TipoSancion tipoSancion)
	{
		this.tipoSancion = tipoSancion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	public Integer getCId ()
	{
		return this.CId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "equipo_c_id")
	public Equipo getEquipo ()
	{
		return this.equipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sancion")
	public Set<Evento> getEventos ()
	{
		return this.eventos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jugador_c_id")
	public Jugador getJugador ()
	{
		return this.jugador;
	}

	@Column(name = "m_estado", length = 1)
	public String getMEstado ()
	{
		return this.MEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sancion")
	public Set<SancionTorneo> getSancionTorneos ()
	{
		return this.sancionTorneos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_sancion_c_id", nullable = false)
	public TipoSancion getTipoSancion ()
	{
		return this.tipoSancion;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public void setEquipo (Equipo equipo)
	{
		this.equipo = equipo;
	}

	public void setEventos (Set<Evento> eventos)
	{
		this.eventos = eventos;
	}

	public void setJugador (Jugador jugador)
	{
		this.jugador = jugador;
	}

	public void setMEstado (String MEstado)
	{
		this.MEstado = MEstado;
	}

	public void setSancionTorneos (Set<SancionTorneo> sancionTorneos)
	{
		this.sancionTorneos = sancionTorneos;
	}

	public void setTipoSancion (TipoSancion tipoSancion)
	{
		this.tipoSancion = tipoSancion;
	}

}
