package com.deportel.futboltel.torneo.modelo;

// Generated 30/01/2011 15:37:39 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sede generated by hbm2java
 */
@Entity
@Table(name = "sede", catalog = "torneo")
public class Sede implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	private Integer				CId;
	private String				DNombre;
	private String				DDescripcion;
	private String				DDireccion;
	private String				DTelefono;
	private String				MEstado;
	private Set<Cancha>			canchas				= new HashSet<Cancha>(0);

	public Sede()
	{
	}

	public Sede(String DNombre, String DDescripcion, String DDireccion, String DTelefono, String MEstado, Set<Cancha> canchas)
	{
		this.DNombre = DNombre;
		this.DDescripcion = DDescripcion;
		this.DDireccion = DDireccion;
		this.DTelefono = DTelefono;
		this.MEstado = MEstado;
		this.canchas = canchas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sede")
	public Set<Cancha> getCanchas ()
	{
		return this.canchas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	public Integer getCId ()
	{
		return this.CId;
	}

	@Column(name = "d_descripcion", length = 300)
	public String getDDescripcion ()
	{
		return this.DDescripcion;
	}

	@Column(name = "d_direccion", length = 45)
	public String getDDireccion ()
	{
		return this.DDireccion;
	}

	@Column(name = "d_nombre", length = 45)
	public String getDNombre ()
	{
		return this.DNombre;
	}

	@Column(name = "d_telefono", length = 45)
	public String getDTelefono ()
	{
		return this.DTelefono;
	}

	@Column(name = "m_estado", length = 1)
	public String getMEstado ()
	{
		return this.MEstado;
	}

	public void setCanchas (Set<Cancha> canchas)
	{
		this.canchas = canchas;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public void setDDescripcion (String DDescripcion)
	{
		this.DDescripcion = DDescripcion;
	}

	public void setDDireccion (String DDireccion)
	{
		this.DDireccion = DDireccion;
	}

	public void setDNombre (String DNombre)
	{
		this.DNombre = DNombre;
	}

	public void setDTelefono (String DTelefono)
	{
		this.DTelefono = DTelefono;
	}

	public void setMEstado (String MEstado)
	{
		this.MEstado = MEstado;
	}

}
