package com.deportel.futboltel.torneo.modelo;

// Generated 30/01/2011 15:37:39 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoSancion generated by hbm2java
 */
@Entity
@Table(name = "tipo_sancion", catalog = "torneo")
public class TipoSancion implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	private Integer				CId;
	private String				DNombre;
	private String				DDescripcion;
	private Integer				NFechasSancion;
	private Character			MAgravada;
	private Integer				NFechasAgregadas;
	private Set<Sancion>		sancions			= new HashSet<Sancion>(0);

	public TipoSancion()
	{
	}

	public TipoSancion(String DNombre, String DDescripcion, Integer NFechasSancion, Character MAgravada, Integer NFechasAgregadas, Set<Sancion> sancions)
	{
		this.DNombre = DNombre;
		this.DDescripcion = DDescripcion;
		this.NFechasSancion = NFechasSancion;
		this.MAgravada = MAgravada;
		this.NFechasAgregadas = NFechasAgregadas;
		this.sancions = sancions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	public Integer getCId ()
	{
		return this.CId;
	}

	@Column(name = "d_descripcion", length = 300)
	public String getDDescripcion ()
	{
		return this.DDescripcion;
	}

	@Column(name = "d_nombre", length = 45)
	public String getDNombre ()
	{
		return this.DNombre;
	}

	@Column(name = "m_agravada", length = 1)
	public Character getMAgravada ()
	{
		return this.MAgravada;
	}

	@Column(name = "n_fechas_agregadas")
	public Integer getNFechasAgregadas ()
	{
		return this.NFechasAgregadas;
	}

	@Column(name = "n_fechas_sancion")
	public Integer getNFechasSancion ()
	{
		return this.NFechasSancion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoSancion")
	public Set<Sancion> getSancions ()
	{
		return this.sancions;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public void setDDescripcion (String DDescripcion)
	{
		this.DDescripcion = DDescripcion;
	}

	public void setDNombre (String DNombre)
	{
		this.DNombre = DNombre;
	}

	public void setMAgravada (Character MAgravada)
	{
		this.MAgravada = MAgravada;
	}

	public void setNFechasAgregadas (Integer NFechasAgregadas)
	{
		this.NFechasAgregadas = NFechasAgregadas;
	}

	public void setNFechasSancion (Integer NFechasSancion)
	{
		this.NFechasSancion = NFechasSancion;
	}

	public void setSancions (Set<Sancion> sancions)
	{
		this.sancions = sancions;
	}

}
