package com.deportel.futboltel.torneo.modelo;

// Generated 30/01/2011 15:37:39 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Torneo generated by hbm2java
 */
@Entity
@Table(name = "torneo", catalog = "torneo")
public class Torneo implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;
	
	private Integer				CId;
	private Categoria			categoria;
	private String				DNombre;
	private String				DDescripcion;
	private String				FFechaInicio;
	private String				FFechaFin;
	private String				MEstado;
	private Set<SancionTorneo>	sancionTorneos		= new HashSet<SancionTorneo>(0);
	private Set<JugadorTorneo>	jugadorTorneos		= new HashSet<JugadorTorneo>(0);
	private Set<Partido>		partidos			= new HashSet<Partido>(0);
	private Set<TorneoEquipo>	torneoEquipos		= new HashSet<TorneoEquipo>(0);
	private Set<Fecha>			fechas				= new HashSet<Fecha>(0);

	public Torneo()
	{
	}

	public Torneo(Categoria categoria)
	{
		this.categoria = categoria;
	}

	public Torneo(Categoria categoria, String DNombre, String DDescripcion, String FFechaInicio, String FFechaFin, String MEstado, Set<SancionTorneo> sancionTorneos, Set<JugadorTorneo> jugadorTorneos, Set<Partido> partidos, Set<TorneoEquipo> torneoEquipos, Set<Fecha> fechas)
	{
		this.categoria = categoria;
		this.DNombre = DNombre;
		this.DDescripcion = DDescripcion;
		this.FFechaInicio = FFechaInicio;
		this.FFechaFin = FFechaFin;
		this.MEstado = MEstado;
		this.sancionTorneos = sancionTorneos;
		this.jugadorTorneos = jugadorTorneos;
		this.partidos = partidos;
		this.torneoEquipos = torneoEquipos;
		this.fechas = fechas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoria_c_id", nullable = false)
	public Categoria getCategoria ()
	{
		return this.categoria;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	public Integer getCId ()
	{
		return this.CId;
	}

	@Column(name = "d_descripcion", length = 300)
	public String getDDescripcion ()
	{
		return this.DDescripcion;
	}

	@Column(name = "d_nombre", length = 45)
	public String getDNombre ()
	{
		return this.DNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "torneo")
	public Set<Fecha> getFechas ()
	{
		return this.fechas;
	}

	@Column(name = "f_fecha_fin", length = 45)
	public String getFFechaFin ()
	{
		return this.FFechaFin;
	}

	@Column(name = "f_fecha_inicio", length = 45)
	public String getFFechaInicio ()
	{
		return this.FFechaInicio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "torneo")
	public Set<JugadorTorneo> getJugadorTorneos ()
	{
		return this.jugadorTorneos;
	}

	@Column(name = "m_estado", length = 1)
	public String getMEstado ()
	{
		return this.MEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "torneo")
	public Set<Partido> getPartidos ()
	{
		return this.partidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "torneo")
	public Set<SancionTorneo> getSancionTorneos ()
	{
		return this.sancionTorneos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "torneo")
	public Set<TorneoEquipo> getTorneoEquipos ()
	{
		return this.torneoEquipos;
	}

	public void setCategoria (Categoria categoria)
	{
		this.categoria = categoria;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public void setDDescripcion (String DDescripcion)
	{
		this.DDescripcion = DDescripcion;
	}

	public void setDNombre (String DNombre)
	{
		this.DNombre = DNombre;
	}

	public void setFechas (Set<Fecha> fechas)
	{
		this.fechas = fechas;
	}

	public void setFFechaFin (String FFechaFin)
	{
		this.FFechaFin = FFechaFin;
	}

	public void setFFechaInicio (String FFechaInicio)
	{
		this.FFechaInicio = FFechaInicio;
	}

	public void setJugadorTorneos (Set<JugadorTorneo> jugadorTorneos)
	{
		this.jugadorTorneos = jugadorTorneos;
	}

	public void setMEstado (String MEstado)
	{
		this.MEstado = MEstado;
	}

	public void setPartidos (Set<Partido> partidos)
	{
		this.partidos = partidos;
	}

	public void setSancionTorneos (Set<SancionTorneo> sancionTorneos)
	{
		this.sancionTorneos = sancionTorneos;
	}

	public void setTorneoEquipos (Set<TorneoEquipo> torneoEquipos)
	{
		this.torneoEquipos = torneoEquipos;
	}

}
