package com.deportel.futboltel.torneo.modelo;

// Generated 30/01/2011 15:37:39 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TorneoEquipo generated by hbm2java
 */
@Entity
@Table(name = "torneo_equipo", catalog = "torneo")
public class TorneoEquipo implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	private Integer				CId;
	private Equipo				equipo;
	private Torneo				torneo;
	private String				MEstado;
	private Integer				NPj;
	private Integer				NPg;
	private Integer				NPp;
	private Integer				NPe;
	private Integer				NGf;
	private Integer				NGc;
	private Integer				NPuntos;

	public TorneoEquipo()
	{
	}

	public TorneoEquipo(Equipo equipo, Torneo torneo)
	{
		this.equipo = equipo;
		this.torneo = torneo;
	}

	public TorneoEquipo(Equipo equipo, Torneo torneo, String MEstado, Integer NPj, Integer NPg, Integer NPp, Integer NPe, Integer NGf, Integer NGc, Integer NPuntos)
	{
		this.equipo = equipo;
		this.torneo = torneo;
		this.MEstado = MEstado;
		this.NPj = NPj;
		this.NPg = NPg;
		this.NPp = NPp;
		this.NPe = NPe;
		this.NGf = NGf;
		this.NGc = NGc;
		this.NPuntos = NPuntos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	public Integer getCId ()
	{
		return this.CId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "equipo_c_id", nullable = false)
	public Equipo getEquipo ()
	{
		return this.equipo;
	}

	@Column(name = "m_estado", length = 1)
	public String getMEstado ()
	{
		return this.MEstado;
	}

	@Column(name = "n_gc")
	public Integer getNGc ()
	{
		return this.NGc;
	}

	@Column(name = "n_gf")
	public Integer getNGf ()
	{
		return this.NGf;
	}

	@Column(name = "n_pe")
	public Integer getNPe ()
	{
		return this.NPe;
	}

	@Column(name = "n_pg")
	public Integer getNPg ()
	{
		return this.NPg;
	}

	@Column(name = "n_pj")
	public Integer getNPj ()
	{
		return this.NPj;
	}

	@Column(name = "n_pp")
	public Integer getNPp ()
	{
		return this.NPp;
	}

	@Column(name = "n_puntos")
	public Integer getNPuntos ()
	{
		return this.NPuntos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "torneo_c_id", nullable = false)
	public Torneo getTorneo ()
	{
		return this.torneo;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public void setEquipo (Equipo equipo)
	{
		this.equipo = equipo;
	}

	public void setMEstado (String MEstado)
	{
		this.MEstado = MEstado;
	}

	public void setNGc (Integer NGc)
	{
		this.NGc = NGc;
	}

	public void setNGf (Integer NGf)
	{
		this.NGf = NGf;
	}

	public void setNPe (Integer NPe)
	{
		this.NPe = NPe;
	}

	public void setNPg (Integer NPg)
	{
		this.NPg = NPg;
	}

	public void setNPj (Integer NPj)
	{
		this.NPj = NPj;
	}

	public void setNPp (Integer NPp)
	{
		this.NPp = NPp;
	}

	public void setNPuntos (Integer NPuntos)
	{
		this.NPuntos = NPuntos;
	}

	public void setTorneo (Torneo torneo)
	{
		this.torneo = torneo;
	}

}
