package com.deportel.futboltel.torneo.modelo;

// Generated 29/01/2012 16:04:23 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ValoresJugadores generated by hbm2java
 */
@Entity
@Table(name = "valores_jugador", catalog = "torneo")
public class ValoresJugador implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	private Integer				CId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "equipo_c_id", nullable = false)
	private Equipo				equipo;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoria_c_id", nullable = false)
	private Categoria			categoria;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jugador_c_id", nullable = false)
	private Jugador				jugador;

	@Column(name = "n_goles")
	private Integer				NGoles;

	@Column(name = "n_amarillas")
	private Integer				NAmarillas;

	@Column(name = "n_fechas_susp")
	private Integer				NFechasSusp;

	@Column(name = "n_pos")
	private Integer				NPos;

	public ValoresJugador()
	{
	}

	public Integer getCId ()
	{
		return this.CId;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public Equipo getEquipo ()
	{
		return this.equipo;
	}

	public void setEquipo (Equipo equipo)
	{
		this.equipo = equipo;
	}

	public Categoria getCategoria ()
	{
		return this.categoria;
	}

	public void setCategoria (Categoria categoria)
	{
		this.categoria = categoria;
	}

	public Jugador getJugador ()
	{
		return this.jugador;
	}

	public void setJugador (Jugador jugador)
	{
		this.jugador = jugador;
	}

	public Integer getNGoles ()
	{
		return this.NGoles;
	}

	public void setNGoles (Integer NGoles)
	{
		this.NGoles = NGoles;
	}

	public Integer getNAmarillas ()
	{
		return this.NAmarillas;
	}

	public void setNAmarillas (Integer NAmarillas)
	{
		this.NAmarillas = NAmarillas;
	}

	public Integer getNFechasSusp ()
	{
		return this.NFechasSusp;
	}

	public void setNFechasSusp (Integer NFechasSusp)
	{
		this.NFechasSusp = NFechasSusp;
	}

	public Integer getNPos ()
	{
		return this.NPos;
	}

	public void setNPos (Integer NPos)
	{
		this.NPos = NPos;
	}

}
