package com.deportel.futboltel.torneo.modelo;

// Generated 29/01/2012 16:04:23 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ValoresEquipos generated by hbm2java
 */
@Entity
@Table(name = "valores_equipo", catalog = "torneo")
public class ValoresEquipo implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	private Integer				CId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "equipo_c_id", nullable = false)
	private Equipo				equipo;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoria_c_id", nullable = false)
	private Categoria			categoria;

	@Column(name = "n_pts")
	private Integer				NPts;

	@Column(name = "n_pos")
	private Integer				NPos;

	@Column(name = "n_pj")
	private Integer				NPj;

	@Column(name = "n_pg")
	private Integer				NPg;

	@Column(name = "n_pe")
	private Integer				NPe;

	@Column(name = "n_pp")
	private Integer				NPp;

	@Column(name = "n_gf")
	private Integer				NGf;

	@Column(name = "n_gc")
	private Integer				NGc;

	public ValoresEquipo()
	{
		this.NGc = 0;
		this.NGf = 0;
		this.NPp = 0;
		this.NPg = 0;
		this.NPe = 0;
		this.NPj = 0;
		this.NPos = 0;
		this.NPts = 0;
	}

	public Integer getCId ()
	{
		return this.CId;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public Equipo getEquipo ()
	{
		return this.equipo;
	}

	public void setEquipo (Equipo equipo)
	{
		this.equipo = equipo;
	}

	public Categoria getCategoria ()
	{
		return this.categoria;
	}

	public void setCategoria (Categoria categoria)
	{
		this.categoria = categoria;
	}

	public Integer getNGf ()
	{
		return this.NGf;
	}

	public void setNGf (Integer NGf)
	{
		this.NGf = NGf;
	}

	public Integer getNGc ()
	{
		return this.NGc;
	}

	public void setNGc (Integer NGc)
	{
		this.NGc = NGc;
	}

	public Integer getNPj ()
	{
		return this.NPj;
	}

	public void setNPj (Integer NPj)
	{
		this.NPj = NPj;
	}

	public Integer getNPg ()
	{
		return this.NPg;
	}

	public void setNPg (Integer NPg)
	{
		this.NPg = NPg;
	}

	public Integer getNPe ()
	{
		return this.NPe;
	}

	public void setNPe (Integer NPe)
	{
		this.NPe = NPe;
	}

	public Integer getNPp ()
	{
		return this.NPp;
	}

	public void setNPp (Integer NPp)
	{
		this.NPp = NPp;
	}

	public Integer getNPts ()
	{
		return this.NPts;
	}

	public void setNPts (Integer NPts)
	{
		this.NPts = NPts;
	}

	public Integer getNPos ()
	{
		return this.NPos;
	}

	public void setNPos (Integer NPos)
	{
		this.NPos = NPos;
	}

}
