package com.deportel.futboltel.torneo.modelo;

// Generated 29/01/2012 16:04:23 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ValoresEquipos generated by hbm2java
 */
@Entity
@Table(name = "valores_partido", catalog = "torneo")
public class ValoresPartido implements java.io.Serializable
{
	private static final long	serialVersionUID	= 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "c_id", unique = true, nullable = false)
	private Integer				CId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_local", nullable = false)
	private Equipo				local;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_visita", nullable = false)
	private Equipo				visita;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoria_c_id", nullable = false)
	private Categoria			categoria;

	@Column(name = "n_gol_local")
	private Integer				NGolLocal;

	@Column(name = "n_gol_visita")
	private Integer				NGolVisita;

	@Column(name = "f_fecha")
	private Date				FFecha;

	public ValoresPartido()
	{
	}

	public Integer getCId ()
	{
		return this.CId;
	}

	public void setCId (Integer CId)
	{
		this.CId = CId;
	}

	public Categoria getCategoria ()
	{
		return this.categoria;
	}

	public void setCategoria (Categoria categoria)
	{
		this.categoria = categoria;
	}

	public Equipo getLocal ()
	{
		return this.local;
	}

	public void setLocal (Equipo local)
	{
		this.local = local;
	}

	public Equipo getVisita ()
	{
		return this.visita;
	}

	public void setVisita (Equipo visita)
	{
		this.visita = visita;
	}

	public Integer getNGolLocal ()
	{
		return this.NGolLocal;
	}

	public void setNGolLocal (Integer nGolLocal)
	{
		this.NGolLocal = nGolLocal;
	}

	public Integer getNGolVisita ()
	{
		return this.NGolVisita;
	}

	public void setNGolVisita (Integer nGolVisita)
	{
		this.NGolVisita = nGolVisita;
	}

	public Date getFFecha ()
	{
		return this.FFecha;
	}

	public void setFFecha (Date fFecha)
	{
		this.FFecha = fFecha;
	}

	//	@Override
	//	public String toString ()
	//	{
	//		StringBuilder sb = new StringBuilder();
	//		sb.
	//		append("Categoria: ").append(this.categoria.getDNombre()).
	//		append(" Local: ").append(this.local.getDNombre()).
	//		append(" Visitante: ").append(this.visita.getDNombre()).
	//		append(" Fecha: ").append(new Date(this.FFecha.getNanos()));
	//		return sb.toString();
	//	}

}
